language: ruby
rvm:
- 2.6.2
script:
  — bundle exec rails db:migrate RAILS_ENV=test
cache: bundler
services:
  - postgresql
addons:
  postgresql: 11 
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres  