language: ruby
rvm:
- 2.6.2
script:
  — bundle exec rails db:migrate
cache: bundler
services:
  - postgresql
addons:
  postgresql: "11" 
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database rails_travis_ci_test;' -U postgres